# Generated by Django 3.2.3 on 2021-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
       
        migrations.CreateModel(
            name='adminlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('enterpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='adminregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('enterpassword', models.CharField(max_length=100)),
            ],
        ),
        
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('enterpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('enterpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
