# Generated by Django 3.2.3 on 2021-06-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_aduserlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduserlist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
