# Generated by Django 3.2.3 on 2021-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_ussleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='addindividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('intime', models.CharField(max_length=100)),
                ('outtime', models.CharField(max_length=100)),
                ('worked', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
